# Generated by Django 3.2.6 on 2021-08-20 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=45)),
                ('slug', models.SlugField(allow_unicode=True, max_length=200)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('corp_code', models.CharField(max_length=6)),
                ('name', models.CharField(db_index=True, max_length=45)),
                ('sales', models.IntegerField(default=0)),
                ('op_profit', models.IntegerField(default=0)),
                ('net_income', models.IntegerField(default=0)),
                ('op_margin', models.FloatField(default=0)),
                ('net_profit_margin', models.FloatField(default=0)),
                ('roe', models.FloatField(default=0)),
                ('debt_ratio', models.FloatField(default=0)),
                ('quick_ratio', models.FloatField(default=0)),
                ('reserve_ratio', models.FloatField(default=0)),
                ('eps', models.IntegerField(default=0)),
                ('per', models.FloatField(default=0)),
                ('bps', models.IntegerField(default=0)),
                ('pbr', models.FloatField(default=0)),
                ('current_stock', models.PositiveIntegerField(default=0)),
                ('market_cap', models.PositiveIntegerField(default=0)),
                ('quarter', models.TextField(max_length=45)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corporations', to='data.category')),
            ],
            options={
                'ordering': ['corp_code'],
            },
        ),
    ]
