# Generated by Django 3.2.6 on 2021-08-20 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_rename_category_name_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
    ]
